INSERT INTO categories (name, description)
VALUES
    ('Concerts', 'Live music and concert events'),
    ('Workshops', 'Practical learning sessions'),
    ('Conferences', 'Technology and professional conferences'),
    ('Sports', 'Sports and physical activity events'),
    ('Gastronomy', 'Food, cooking and culinary events'),
    ('Festivals', 'Large cultural and entertainment festivals'),
    ('Theater', 'Stage plays and performing arts'),
    ('Rock', 'Rock music events and concerts')
    ON CONFLICT (name) DO NOTHING;

INSERT INTO venues (name, address, capacity, city)
VALUES
    ('Movistar Arena', 'Calle 63 # 60-80', 14000, 'Bogotá'),
    ('Centro de Convenciones Ágora', 'Avenida Calle 24 # 38-47', 4000, 'Bogotá'),
    ('Teatro Metropolitano', 'Calle 41 # 57-30', 1600, 'Medellín'),
    ('Plaza Mayor', 'Calle 41 # 55-80', 3000, 'Medellín'),
    ('Centro de Eventos Valle del Pacífico', 'Autopista Cali-Yumbo', 5000, 'Cali'),
    ('Teatro Municipal Enrique Buenaventura', 'Carrera 5 # 6-64', 1200, 'Cali'),
    ('Centro de Convenciones Puerta de Oro', 'Vía 40 # 79B-06', 3500, 'Barranquilla'),
    ('Teatro Amira de la Rosa', 'Carrera 54 # 52-258', 900, 'Barranquilla'),
    ('Centro de Convenciones Cartagena', 'Calle 24 # 8A-344', 2500, 'Cartagena'),
    ('Teatro Adolfo Mejía', 'Plaza de la Merced', 700, 'Cartagena');

WITH venue_ref AS (
    SELECT id
    FROM venues
    WHERE name = 'Movistar Arena'
      AND city = 'Bogotá'
    ORDER BY id
    LIMIT 1
    ),
    category_ref AS (
SELECT id
FROM categories
WHERE name = 'Rock'
    LIMIT 1
    ),
    inserted_event AS (
INSERT INTO events (name, event_date, description, active, venue_id)
SELECT
    'Concierto de ROCK',
    DATE '2026-07-20',
    'Evento especial de rock creado para validar búsqueda parcial e insensible a mayúsculas.',
    true,
    venue_ref.id
FROM venue_ref
    RETURNING id
    )
INSERT INTO events_categories (event_id, category_id)
SELECT inserted_event.id, category_ref.id
FROM inserted_event, category_ref
    ON CONFLICT DO NOTHING;

WITH venue_pool AS (
    SELECT
        id,
        ROW_NUMBER() OVER (ORDER BY id) AS rn,
        COUNT(*) OVER () AS total
    FROM venues
),
     base_seed AS (
         SELECT
             gs AS n,
             CASE (gs % 7)
                 WHEN 0 THEN 'Concerts'
                 WHEN 1 THEN 'Workshops'
                 WHEN 2 THEN 'Conferences'
                 WHEN 3 THEN 'Sports'
                 WHEN 4 THEN 'Gastronomy'
                 WHEN 5 THEN 'Festivals'
                 ELSE 'Theater'
                 END AS category_name,
             CASE (gs % 7)
                 WHEN 0 THEN 'Concert Night'
                 WHEN 1 THEN 'Professional Workshop'
                 WHEN 2 THEN 'Tech Conference'
                 WHEN 3 THEN 'Sports Meeting'
                 WHEN 4 THEN 'Gastronomy Fair'
                 WHEN 5 THEN 'Cultural Festival'
                 ELSE 'Theater Show'
                 END AS event_type
         FROM generate_series(1, 200) AS gs
     ),
     event_seed AS (
         SELECT
             n,
             category_name,
             event_type,
             'Eventify Seed Event ' || n || ' - ' || event_type AS event_name
         FROM base_seed
     ),
     inserted_events AS (
INSERT INTO events (name, event_date, description, active, venue_id)
SELECT
    es.event_name,
    DATE '2026-01-01' + (es.n % 365),
    'Seed event generated by Flyway V3 for performance, pagination and filtering validation.',
    true,
    (
        SELECT vp.id
        FROM venue_pool vp
        WHERE vp.rn = ((es.n - 1) % (SELECT total FROM venue_pool LIMIT 1)) + 1
    LIMIT 1
    )
FROM event_seed es
    RETURNING id, name
    )
INSERT INTO events_categories (event_id, category_id)
SELECT
    ie.id,
    c.id
FROM inserted_events ie
         JOIN event_seed es ON es.event_name = ie.name
         JOIN categories c ON c.name = es.category_name
    ON CONFLICT DO NOTHING;

WITH base_seed AS (
    SELECT
        gs AS n,
        CASE ((gs + 2) % 7)
    WHEN 0 THEN 'Concerts'
            WHEN 1 THEN 'Workshops'
            WHEN 2 THEN 'Conferences'
            WHEN 3 THEN 'Sports'
            WHEN 4 THEN 'Gastronomy'
            WHEN 5 THEN 'Festivals'
            ELSE 'Theater'
END AS secondary_category_name,
        CASE (gs % 7)
            WHEN 0 THEN 'Concert Night'
            WHEN 1 THEN 'Professional Workshop'
            WHEN 2 THEN 'Tech Conference'
            WHEN 3 THEN 'Sports Meeting'
            WHEN 4 THEN 'Gastronomy Fair'
            WHEN 5 THEN 'Cultural Festival'
            ELSE 'Theater Show'
END AS event_type
    FROM generate_series(1, 200) AS gs
),
event_seed AS (
    SELECT
        n,
        secondary_category_name,
        'Eventify Seed Event ' || n || ' - ' || event_type AS event_name
    FROM base_seed
)
INSERT INTO events_categories (event_id, category_id)
SELECT
    e.id,
    c.id
FROM event_seed es
         JOIN events e ON e.name = es.event_name
         JOIN categories c ON c.name = es.secondary_category_name
WHERE es.n % 3 = 0
ON CONFLICT DO NOTHING;